{% set version = '1.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-forestplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/forestplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forestplot/forestplot_{{ version }}.tar.gz
  sha256: 6d23e5ed32d987bb025c4a9091883e83e3e7a0bb5cc2377d386bc91eccefdeb3

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-magrittr
  run:
    - r-base
    - r-checkmate
    - r-magrittr

test:
  commands:
    - $R -e "library('forestplot')"           # [not win]
    - "\"%R%\" -e \"library('forestplot')\""  # [win]

about:
  home: http://gforge.se/packages/
  license: GPL-2
  summary: A forest plot that allows for multiple confidence intervals per row, custom fonts
    for each text element, custom confidence intervals, text mixed with expressions,
    and more. The aim is to extend the use of forest plots beyond meta-analyses. This
    is a more general version of the original 'rmeta' package's forestplot() function
    and relies heavily on the 'grid' package.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: forestplot
# Version: 1.8
# Date: 2019-06-01
# Title: Advanced Forest Plot Using 'grid' Graphics
# Authors@R: c(person(given = "Max", family = "Gordon", role = c("aut", "cre"), email = "max@gforge.se"), person(given = "Thomas", family = "Lumley", role = c("aut", "ctb")))
# Description: A forest plot that allows for multiple confidence intervals per row, custom fonts for each text element, custom confidence intervals, text mixed with expressions, and more. The aim is to extend the use of forest plots beyond meta-analyses. This is a more general version of the original 'rmeta' package's forestplot() function and relies heavily on the 'grid' package.
# License: GPL-2
# URL: http://gforge.se/packages/
# BugReports: https://github.com/gforge/forestplot/issues
# Biarch: yes
# Depends: grid, magrittr, checkmate
# Suggests: testthat, abind, knitr, rmarkdown
# Encoding: UTF-8
# NeedsCompilation: no
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Packaged: 2019-06-01 08:19:51 UTC; max
# Author: Max Gordon [aut, cre], Thomas Lumley [aut, ctb]
# Maintainer: Max Gordon <max@gforge.se>
# Repository: CRAN
# Date/Publication: 2019-06-01 08:50:03 UTC
