travis:
  secure:
    BINSTAR_TOKEN: KpCcoG6+29P8R5HHja0/pYpoZU1Mw2kv5Gr/f16c6PbFO4HemEr8ETAPWalngG7yb0AoM09rmoFb3CfuwNRVNbxAfyOZH4fH0extLNhU7YpU3oOIaaqR1lfx4qDyjhojhVVtB7gY38vMhGZFoUNL07NXODTNQaFrtUHY1OqDB1PksYWKftJ8d7KUKSgb9cNQ8ROlCJ7J85fynoOItcG0R1jzngHeYFte2Q3dKI2GNl1kW7n0L5/ZdrFMI7vdcW/enakQ5aaEODCYWLKmmZ8mbCvkg/p/unFw9wmrfQpZCS5sy4/5uT0jKzDRSb18pwNrr8zQtOg2xZbrLlsfvEeYpvFG11PnzRN8eizSvgJyj3SWEKF5sH1bvuwrMbEdM692uOh0pgi8IbCM8qbxmx7BhtmJdMjoQXfXwVLLcZENuKV6vAPC0hINashG+FeWKcvPEjiq2jL3ZUkkj7TRlZ8tEEut5jqmA6r7IKNh6efxewXZUNdjCri16Fxdn3Rn47BMj4S0OofeeWEe9egh9MLa1WXv3B7wre/hf8fp9Qo2vogRiOveZ+7yxQhmaztG6sfGMWYKFL2wxHJnRhwp885fZDcWSDwDTVqJR2DMqrqxPhTxwfct1n1hO/6iwjJxmuBplOs78onzkDQTyNIEBXJym3ZM3hTAKWsBgTvHaynHGBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
