appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ILGfjFjjfXvC1+mVNlZWNCydEg90hh4oZ8vCRJu5lR8OuSHw9GimgP1XQZdbXjrLqotdluUQ81blk6Xk6Lrr8RFkWKuZiddJILWRuaXO8HUMmNrcXSm/rt72V79WAYgLg7wYzVTjw1O264AMq4wcJUlKlyZzc4n4sbA0XKwZn8nGMOrkymnYjVhTQAnjUkpxKwN5HIt+XO8SPF/P+8IgIPA+VNloW+82sxoQswdf21CCDMiJ6pONFxWSo+tBe/lwU8/u9yuih77pSaWbq0yLhTOUV6Oq2hBr9lfP2Rf6TTvdcgtiJCWHKUT3GBGvOPXXoDt/qnmttVjJnHnWLzT5VcfBqPHg0I421QW80KRxZ/E1r7MueQuJrFwBANL6XxUkHHn181j9c6lUpbgrCkew0InEmUpIR9bpZwWcnIUFxRHFeWb3hj6Sq1jKFYbNKaCMLO14R5ktguzaIBX/sFox9CsqCBDnr9CnnEHdMtdhcmwDGrfvbE/H7QKvuokLReR2dzsh/tGcQ3TMtv+QTwzOH6rITAGobyTykpK0CsA4Z1T6dU42VHcHDEF5wEPk2NGai68+SVMwlirecM36WLj4h0UjFjfg+3I/mavHWK3Q4QDQbkhr7Dnw3t9ipt2tPNLUJwujywU1FgXnCAgd8Qi9vBWT49mGSPLNoJhZFziM8so=}
