travis:
  secure:
    BINSTAR_TOKEN: l1wqE+XDg3nElJiotOxnN2II8zts7qIB21KXUG9qaJi+DcVuAvsGskwMWxFYSPpyMexRmNfQ3LPb7Uc6ZGll03x9E25oMcyTXJt+NsDVhqlsItrbXGUQtr4qbGbuYacyKBDBRM2qhHkBSlZujtyL0CCsCxmgWn7+s/dWHLnAOwr+4/yNJMNDEiFaOKP1dGuSVsZTgqtSu1cbKocwglQkbLMRnXnu02rs1Afbf8twBz/LA6Zfw3UTxrEPgCSQF2UUaQ6b6gqnIwYV/NqvNsQQUeCX/FoV8dvlPmPuwvrCAG+YEj4/Sgj4yhJxspFQaJl7/nv1AkbNd0rtFewEx9EmpmsxmhpPo8hER0rX9ZPN/fwqe5KVL7SJIC7OgP1Tp2xU2yCpDHSMXrmOgSM9SWxNznduhf4mG98U5g2Yj6pJjHzi3tr6+QQR536dEFdHZ2w3yjQffONSRCWE7HH7i//1GJBA+3Guemdq2bpRGpo9mD302EDnDW/L1x8O8N8XNLtLx9SwY2RaZjG/cdlstwL0HCmroA4FYOjo8CiZZ6XNVK2MjkHukX99f3Nx7bPAw7lvFB220SsJmecl0zP7rPqvmei/uh880zYjGkExMB0cKPsySQBB7ghOtGdIPY77HPzLJgh1zYkzXQeUdA68nEqioU9a2thnGBzdE6CpP5F/WZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
